# https://github.com/phitronio/SDT-Django/tree/main/PhiMart
# Classy Django REST Framework: https://www.cdrf.co/

"""
Django settings for phi_mart project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1f^)8a)#2x9^dubiz_7z)2spt*r4sltsut8u%kcq=c-^bw061%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	#
	'drf_yasg', # yasg: Yet Another Swagger Generator. https://drf-yasg.readthedocs.io/en/stable/readme.html
	'rest_framework',
	'rest_framework_simplejwt',
	
	"debug_toolbar",  # https://django-debug-toolbar.readthedocs.io/en/latest/installation.html
	'djoser',
	'django_filters',
	#
	'api',
	'orders',
	'products',
	'users',	
]

MIDDLEWARE = [
	"debug_toolbar.middleware.DebugToolbarMiddleware", # ---
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'phi_mart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'phi_mart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------

AUTH_USER_MODEL = 'users.User'

INTERNAL_IPS = ["127.0.0.1",]  # The Debug Toolbar is shown only if your IP address is listed in Django’s INTERNAL_IPS

#from rest_framework.permissions import IsAuthenticated
REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,  # dont convert decimal to string
    'DEFAULT_AUTHENTICATION_CLASSES': (        
        'rest_framework.authentication.SessionAuthentication',  # 1. SessionAuthentication for the browsable API        
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # 2. JWTAuthentication for token-based clients		
    ),
	'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.IsAuthenticated',
		'rest_framework.permissions.AllowAny',
    ]

}



SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),	
	# ^ When making authenticated requests, Authorization: JWT <token> , instead of Authorization: Bearer <token> , 'AUTH_HEADER_TYPES': ('JWT', 'Bearer')	Accepts both formats
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    # "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    # "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

DJOSER = {
    'SERIALIZERS': {
        'user_create': 'users.serializers.UserCreateSerializer',  # http://127.0.0.1:8000/api/auth/users/
        'current_user': 'users.serializers.UserSerializer', # http://127.0.0.1:8000/api/auth/users/me
    },
}

SWAGGER_SETTINGS = {  # module 25.4
   'SECURITY_DEFINITIONS': {      
      'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
			'description': 'Enter your JWT token in the format: `JWT <your_token>`'
      }
   }
}

"""
djoser,
Token Obtain Pair:
http://127.0.0.1:8000/api/auth/jwt/create
email:anup@example.com
password:aB@12345
----
HTTP 200 OK
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MzczNDg2MiwiaWF0IjoxNzUzNjQ4NDYyLCJqdGkiOiI5MjA5ZDBkNGMwY2Y0N2YwYTFkMjhhOGIzMTE3OGM2ZSIsInVzZXJfaWQiOiIyIn0.k2PNVv-cjYaIXesbyw9UbSQZZb1cD78cCJcoAJot2fQ",
    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNzM0ODYyLCJpYXQiOjE3NTM2NDg0NjIsImp0aSI6ImY2Y2RmNzAyMThhZTQ4MWNhYzg5NGEwZjIwNmFjNGU1IiwidXNlcl9pZCI6IjIifQ.hYGl8nxcnOrzK3SHhjFk8CRTI-SBPR6ZKOyeCLhokQE"
}

refresh token:
http://127.0.0.1:8000/api/auth/jwt/refresh
"""

"""
simple jwt only:
http://127.0.0.1:8000/api/token/
http://127.0.0.1:8000/api/token/refresh/
"""